### ISSUE TITLE
Doesn't work?

### ISSUE THREAD

**Issue by john-cj** [sirbrillig/mixed-indent-warning#23]
It seems it doesn't work on my Atom 1.34.

* All dependencies are installed (linter, linter-ui-default, intentions, busy-signal).
* Already tried to restart Atom.
* "Force indentations style" is set to "spaces".

However, in the file with mixed tabs and spaces used as indentation - it shows zero errors/warnings.

![untitled](https://user-images.githubusercontent.com/18004961/51842243-7d9f5e00-2321-11e9-8d86-1b683c9b33c6.png)

**Comment by Arcanemagus** [comment]
In the [v2.3.0 release](https://github.com/steelbrain/linter/releases/tag/v2.3.0) of `linter` support for the v1 API was removed, breaking semver. This means that this provider is no longer supported by the current version of `linter`.

To get this provider working again it will need to be upgrade to the v2 API, a guide for accomplishing that can be found here: [Upgrading to Standard Linter v2](https://github.com/steelbrain/linter/blob/v2.3.0/docs/guides/upgrading-to-standard-linter-v2.md).

Until this is fixed in order to use this provider you will need to downgrade to the last version of `linter` that supports the v1 API, you can do this with `apm install linter@2.2.0`.

**Comment by john-cj** [comment]
Thank you very much for detailed answer. So, I close this issue.
